### PR TITLE
Regex i flag

### PR DESCRIPTION
**Pull request by amaanq**
Upstream ts now supports this :)

### CODE REVIEW

**Comment by briot** [comment]
Thanks for the patch.  I had noticed this change upstream, but it is nice.
Also I am curious how you found the unnecessary conflicts ? I had spent quite some time trying to find those conflicts, and maybe there are more efficient ways than just trying to remove them one by one :-)

**Comment by amaanq** [comment]
using the rust cli app on master will warn you about unnecessary conflicts :grin:

**Comment by briot** [comment]
Nice !
I just noticed the testsuite was broken with this pull, I am investigating

**Comment by briot** [comment]
I guess I am a bit lost with all those upstreams.
This repository uses `npm` to get its dependencies.  For this one, we have a tree-sitter 0.20.5 package in npm, which dates back to April 5th and doesn't seem to include the case-insensitive changes (though no error is displayed).
I could also modify Cargo.toml to have an explicit dependency on the tree-sitter crate 0.20.10 (the latest I could find).
Lastly, if I go to https://github.com/tree-sitter/tree-sitter the latest version is documented as 0.20.8.

TBH, I do not remember why I went with npm in the first place, maybe the recommendation nowadays is to directly go with Rust cli and forgo npm altogether ?

**Pull request merged**
